name: QA_CI

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to environment'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install docker-ce -y
        sudo usermod -aG docker $USER

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker login -u santiagoambricca -p ${{ secrets.TOKEN_DOCKERHUB }}
        docker build -t santiagoambricca/org_proveedores_qa:latest ./docker
        docker push santiagoambricca/org_proveedores_qa:latest

    - name: SSH into EC2 instance and deploy
      if: github.event.inputs.deploy == 'true'
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@44.206.233.112 "docker pull santiagoambricca/org_proveedores_qa:latest && docker run -d -p 80:80 santiagoambricca/org_proveedores_qa:latest"

    - name: Verify service is running
      if: github.event.inputs.deploy == 'true'
      run: |
        curl http://44.206.233.112
