name: Remover Directorio
on:
  push:
    branches:
      - proveedores
env:
  SSH_PRIVATE_KEY: ${{ secrets.PEM_AWS_QA }}
  REMOTE_USER: ec2-user
  REMOTE_HOST: ${{ secrets.EC2_IP_QA_PUBLICO }}
  APP_NAME: app.js
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ./key.pem
          script: |
            sudo rm -rf /opt/montoto || true
